insert into public.code_master (group_name, code, label, sort_order) values

  ('job_role', 'frontend',  '프론트엔드',      1),
  ('job_role', 'backend',   '백엔드',          2),
  ('job_role', 'fullstack', '풀스택',          3),
  ('job_role', 'android',   '안드로이드',      4),
  ('job_role', 'ios',       'iOS',             5),
  ('job_role', 'devops',    '데브옵스·인프라', 6),
  ('job_role', 'data_ai',   '데이터·AI',       7),
  ('job_role', 'game',      '게임',            8),
  ('job_role', 'security',  '보안',            9),
  ('job_role', 'qa',        'QA',             10),
  ('job_role', 'embedded',  '임베디드',       11),
  ('job_role', 'pm',        'PM·기획',        12),
  ('job_role', 'designer',  'UI/UX 디자인',   13),

  ('company_size', 'startup',        '스타트업',   1),
  ('company_size', 'small',          '중소기업',   2),
  ('company_size', 'midsize',        '중견기업',   3),
  ('company_size', 'large',          '대기업',     4),
  ('company_size', 'foreign',        '외국계',     5),
  ('company_size', 'public_finance', '공공·금융',  6),

  ('industry', 'it_software', 'IT·소프트웨어',   1),
  ('industry', 'platform',    '플랫폼·포털',     2),
  ('industry', 'game',        '게임',            3),
  ('industry', 'fintech',     '핀테크·금융',     4),
  ('industry', 'ecommerce',   '이커머스',        5),
  ('industry', 'ai_data',     'AI·데이터',       6),
  ('industry', 'security',    '보안',            7),
  ('industry', 'mobility',    '모빌리티',        8),
  ('industry', 'healthcare',  '헬스케어',        9),
  ('industry', 'education',   '교육',           10),
  ('industry', 'si_sm',       'SI·SM',          11),
  ('industry', 'media',       '미디어·콘텐츠',  12),

  ('tech_stack', 'html',         'HTML',          1),
  ('tech_stack', 'css',          'CSS',           2),
  ('tech_stack', 'javascript',   'JavaScript',    3),
  ('tech_stack', 'typescript',   'TypeScript',    4),
  ('tech_stack', 'react',        'React',         5),
  ('tech_stack', 'nextjs',       'Next.js',       6),
  ('tech_stack', 'vue',          'Vue',           7),
  ('tech_stack', 'svelte',       'Svelte',        8),
  ('tech_stack', 'nodejs',       'Node.js',       9),
  ('tech_stack', 'nestjs',       'NestJS',       10),
  ('tech_stack', 'spring',       'Spring',       11),
  ('tech_stack', 'java',         'Java',         12),
  ('tech_stack', 'kotlin',       'Kotlin',       13),
  ('tech_stack', 'python',       'Python',       14),
  ('tech_stack', 'django',       'Django',       15),
  ('tech_stack', 'fastapi',      'FastAPI',      16),
  ('tech_stack', 'go',           'Go',           17),
  ('tech_stack', 'rust',         'Rust',         18),
  ('tech_stack', 'c',            'C',            19),
  ('tech_stack', 'cpp',          'C++',          20),
  ('tech_stack', 'csharp',       'C#',           21),
  ('tech_stack', 'dotnet',       '.NET',         22),
  ('tech_stack', 'php',          'PHP',          23),
  ('tech_stack', 'ruby',         'Ruby',         24),
  ('tech_stack', 'swift',        'Swift',        25),
  ('tech_stack', 'flutter',      'Flutter',      26),
  ('tech_stack', 'dart',         'Dart',         27),
  ('tech_stack', 'react_native', 'React Native', 28),
  ('tech_stack', 'mysql',        'MySQL',        29),
  ('tech_stack', 'postgresql',   'PostgreSQL',   30),
  ('tech_stack', 'mongodb',      'MongoDB',      31),
  ('tech_stack', 'redis',        'Redis',        32),
  ('tech_stack', 'graphql',      'GraphQL',      33),
  ('tech_stack', 'docker',       'Docker',       34),
  ('tech_stack', 'kubernetes',   'Kubernetes',   35),
  ('tech_stack', 'aws',          'AWS',          36),
  ('tech_stack', 'gcp',          'GCP',          37),
  ('tech_stack', 'azure',        'Azure',        38),
  ('tech_stack', 'firebase',     'Firebase',     39),
  ('tech_stack', 'supabase',     'Supabase',     40),
  ('tech_stack', 'git',          'Git',          41),
  ('tech_stack', 'figma',        'Figma',        42),

  ('interest_field', 'frontend',  '프론트엔드',  1),
  ('interest_field', 'backend',   '백엔드',      2),
  ('interest_field', 'fullstack', '풀스택',      3),
  ('interest_field', 'mobile',    '모바일',      4),
  ('interest_field', 'data',      '데이터',      5),
  ('interest_field', 'ai_ml',     'AI·ML',       6),
  ('interest_field', 'devops',    'DevOps',      7),
  ('interest_field', 'security',  '보안',        8),
  ('interest_field', 'a11y',      '웹 접근성',   9),
  ('interest_field', 'planning',  '기획',       10),
  ('interest_field', 'design',    '디자인',     11),

  ('interview_channel', 'online',          '온라인 지원',      1),
  ('interview_channel', 'referral_friend', '지인 추천',        2),
  ('interview_channel', 'referral_school', '학교 추천',        3),
  ('interview_channel', 'job_fair',        '채용 박람회',      4),
  ('interview_channel', 'recruiter',       '채용 담당자 제안', 5),
  ('interview_channel', 'etc',             '기타',             6),

  ('pass_result', 'pass',    '합격',   1),
  ('pass_result', 'waiting', '대기',   2),
  ('pass_result', 'fail',    '불합격', 3),

  ('difficulty', 'easy',   '쉬움',   1),
  ('difficulty', 'normal', '보통',   2),
  ('difficulty', 'hard',   '어려움', 3),

  ('language_level', 'high', '상', 1),
  ('language_level', 'mid',  '중', 2),
  ('language_level', 'low',  '하', 3),

  ('education_level', 'high_school', '고졸',   1),
  ('education_level', 'associate',   '초대졸', 2),
  ('education_level', 'bachelor',    '대졸',   3),
  ('education_level', 'master',      '석사',   4),
  ('education_level', 'doctor',      '박사',   5),

  ('school_type', 'high_school', '고등학교', 1),
  ('school_type', 'college',     '전문대',   2),
  ('school_type', 'university',  '대학교',   3),
  ('school_type', 'graduate',    '대학원',   4),

  ('career_level', 'entry',  '신입',   1),
  ('career_level', '1_3',    '1~3년',  2),
  ('career_level', '3_5',    '3~5년',  3),
  ('career_level', '5_plus', '5년+',   4),

  ('edu_status', 'enrolled',  '재학', 1),
  ('edu_status', 'leave',     '휴학', 2),
  ('edu_status', 'graduated', '졸업', 3),
  ('edu_status', 'dropped',   '중퇴', 4),

  ('interviewer_style', 'friendly',  '친절한',    1),
  ('interviewer_style', 'neutral',   '보통',      2),
  ('interviewer_style', 'pressure',  '압박하는',  3),
  ('interviewer_style', 'technical', '기술 심층', 4),

  ('interview_category', 'intro',       '자기소개',     1),
  ('interview_category', 'tech1',       '기술질문1',    2),
  ('interview_category', 'tech2',       '기술질문2',    3),
  ('interview_category', 'personality', '인성질문',     4),
  ('interview_category', 'closing',     '마무리질문',   5),

  ('portfolio_category', 'web', '웹',     1),
  ('portfolio_category', 'app', '앱',     2)

on conflict (group_name, code) do update
  set label      = excluded.label,
      sort_order = excluded.sort_order,
      is_active  = true;
