insert into public.companies (
  slug, name, industry_code, size_code, job_role_codes, location,
  tagline, description, tags, homepage, employee_count, avg_salary_text,
  rating, rating_dimensions, salary_detail, hiring_status,
  core_values, services, benefits, highlights
) values

('naver', '네이버', 'platform', 'large',
 '{frontend,backend,fullstack,android,ios,devops,data_ai,designer,pm}', '경기 성남',
 '대한민국 대표 인터넷 플랫폼 기업',
 '검색, 커머스, 콘텐츠, 클라우드까지 아우르는 국내 최대 인터넷 플랫폼 기업입니다. 자체 개발한 검색 엔진과 AI 기술을 기반으로 다양한 서비스를 운영하며, 기술 조직 규모가 크고 사내 개발 문화가 잘 정착되어 있습니다.',
 '{검색,AI,클라우드,커머스}', 'https://www.navercorp.com', 4500, '5,800만원',
 4.3, '{"salary":4.4,"wlb":4.2,"culture":4.3,"growth":4.4}'::jsonb,
 '{"overall":5800,"entry":4200,"top25":8200}'::jsonb, '상시 채용',
 '[{"icon":"rocket_launch","title":"기술 중심","desc":"자체 기술로 문제를 해결합니다"},{"icon":"groups","title":"협업","desc":"조직 간 경계 없이 협업합니다"},{"icon":"public","title":"글로벌","desc":"세계 시장을 향해 확장합니다"},{"icon":"school","title":"성장","desc":"구성원의 성장을 지원합니다"}]'::jsonb,
 '[{"name":"네이버 검색"},{"name":"네이버 지도"},{"name":"네이버 웹툰"},{"name":"네이버페이"},{"name":"네이버 클라우드"}]'::jsonb,
 '[{"icon":"restaurant","title":"식사 지원","desc":"사내 식당 및 카페 운영"},{"icon":"medical_services","title":"건강검진","desc":"본인 및 가족 건강검진"},{"icon":"school","title":"교육비 지원","desc":"도서·강의·컨퍼런스 지원"},{"icon":"child_care","title":"육아 지원","desc":"어린이집 및 육아휴직"},{"icon":"schedule","title":"유연근무","desc":"책임근무제 운영"}]'::jsonb,
 '["국내 최대 규모의 인터넷 플랫폼","검색·AI 자체 기술력 보유","개발 직군 채용 규모가 큼","사내 기술 컨퍼런스 DEVIEW 운영"]'::jsonb),

('kakao', '카카오', 'platform', 'large',
 '{frontend,backend,android,ios,devops,data_ai,designer,pm}', '경기 성남',
 '사람과 사람, 사람과 기술을 연결',
 '카카오톡을 중심으로 메신저, 커머스, 모빌리티, 페이 등 생활 전반의 서비스를 제공합니다. 다수의 계열사가 각 영역을 담당하는 구조이며, 개발 직군의 도메인 선택 폭이 넓습니다.',
 '{메신저,플랫폼,모빌리티,핀테크}', 'https://www.kakaocorp.com', 3800, '5,600만원',
 4.1, '{"salary":4.2,"wlb":4.0,"culture":4.1,"growth":4.0}'::jsonb,
 '{"overall":5600,"entry":4100,"top25":7900}'::jsonb, '상시 채용',
 '[{"icon":"handshake","title":"신뢰","desc":"수평적 소통을 지향합니다"},{"icon":"lightbulb","title":"도전","desc":"새로운 시도를 장려합니다"},{"icon":"diversity_3","title":"다양성","desc":"서로 다름을 존중합니다"},{"icon":"trending_up","title":"성장","desc":"함께 성장합니다"}]'::jsonb,
 '[{"name":"카카오톡"},{"name":"카카오맵"},{"name":"카카오페이"},{"name":"카카오T"},{"name":"다음"}]'::jsonb,
 '[{"icon":"restaurant","title":"식사 지원","desc":"사내 식당 운영"},{"icon":"medical_services","title":"의료비 지원","desc":"본인·가족 의료비"},{"icon":"beach_access","title":"리프레시 휴가","desc":"3년마다 장기 휴가"},{"icon":"school","title":"자기계발","desc":"교육비 및 도서 지원"},{"icon":"schedule","title":"유연근무","desc":"근무 시간 선택제"}]'::jsonb,
 '["카카오톡 기반의 국민 플랫폼","계열사별 도메인이 다양함","수평적 호칭 문화(영어 이름)","공채와 상시 채용 병행"]'::jsonb),

('line', '라인', 'platform', 'large',
 '{frontend,backend,android,ios,devops,data_ai,security}', '서울',
 '글로벌 메신저 플랫폼',
 '일본·대만·태국을 중심으로 사용되는 글로벌 메신저 서비스를 운영합니다. 해외 법인과 협업하는 개발 환경이며 영어 사용 빈도가 높은 편입니다.',
 '{메신저,글로벌,핀테크}', 'https://linepluscorp.com', 3000, '6,000만원',
 4.2, '{"salary":4.4,"wlb":4.1,"culture":4.2,"growth":4.2}'::jsonb,
 '{"overall":6000,"entry":4400,"top25":8500}'::jsonb, '상시 채용',
 '[{"icon":"public","title":"글로벌","desc":"여러 나라의 동료와 일합니다"},{"icon":"speed","title":"속도","desc":"빠르게 만들고 개선합니다"},{"icon":"psychology","title":"자율","desc":"스스로 판단하고 실행합니다"},{"icon":"verified","title":"품질","desc":"높은 완성도를 추구합니다"}]'::jsonb,
 '[{"name":"LINE 메신저"},{"name":"LINE 스티커"},{"name":"LINE 페이"}]'::jsonb,
 '[{"icon":"flight","title":"해외 근무 기회","desc":"글로벌 법인 교류"},{"icon":"restaurant","title":"식사 지원","desc":"식대 지원"},{"icon":"school","title":"어학 지원","desc":"영어·일본어 교육"},{"icon":"schedule","title":"유연근무","desc":"자율 출퇴근"}]'::jsonb,
 '["아시아 전역에서 쓰이는 메신저","글로벌 협업 환경","영어·일본어 활용 기회","기술 블로그 활발"]'::jsonb),

('coupang', '쿠팡', 'ecommerce', 'large',
 '{frontend,backend,fullstack,android,ios,devops,data_ai}', '서울',
 '고객이 없는 세상을 상상할 수 없게',
 '자체 물류망을 기반으로 한 이커머스 기업입니다. 대규모 트래픽과 물류 시스템을 다루며, 실리콘밸리식 엔지니어링 문화를 지향합니다.',
 '{이커머스,물류,대용량트래픽}', 'https://www.coupang.jobs', 5000, '6,500만원',
 3.9, '{"salary":4.6,"wlb":3.3,"culture":3.8,"growth":4.1}'::jsonb,
 '{"overall":6500,"entry":4800,"top25":9500}'::jsonb, '상시 채용',
 '[{"icon":"person","title":"고객 집착","desc":"고객에서 거꾸로 출발합니다"},{"icon":"insights","title":"데이터","desc":"근거로 의사결정합니다"},{"icon":"bolt","title":"실행","desc":"빠르게 실행합니다"},{"icon":"engineering","title":"소유의식","desc":"끝까지 책임집니다"}]'::jsonb,
 '[{"name":"로켓배송"},{"name":"쿠팡플레이"},{"name":"쿠팡이츠"}]'::jsonb,
 '[{"icon":"payments","title":"높은 보상","desc":"업계 상위권 연봉"},{"icon":"laptop_mac","title":"장비 지원","desc":"고사양 개발 장비"},{"icon":"language","title":"영어 환경","desc":"글로벌 엔지니어와 협업"},{"icon":"medical_services","title":"건강검진","desc":"종합 건강검진"}]'::jsonb,
 '["대규모 트래픽 경험 가능","영어 사용 비중이 높음","실리콘밸리식 엔지니어링 문화","보상 수준이 업계 상위권"]'::jsonb),

('woowahan', '우아한형제들', 'platform', 'large',
 '{frontend,backend,android,ios,devops,data_ai,designer}', '서울',
 '좋은 음식을 먹고 싶은 곳에서',
 '배달의민족을 운영하는 푸드테크 기업입니다. 개발 문화와 사내 교육 프로그램이 잘 알려져 있고, 기술 공유 활동이 활발합니다.',
 '{푸드테크,플랫폼,MSA}', 'https://www.woowahan.com', 2000, '5,500만원',
 4.4, '{"salary":4.3,"wlb":4.5,"culture":4.6,"growth":4.4}'::jsonb,
 '{"overall":5500,"entry":4200,"top25":7600}'::jsonb, '상시 채용',
 '[{"icon":"favorite","title":"규율 위의 자율","desc":"원칙 위에서 자율적으로"},{"icon":"forum","title":"솔직함","desc":"솔직하게 소통합니다"},{"icon":"school","title":"학습","desc":"배움을 나눕니다"},{"icon":"emoji_objects","title":"창의","desc":"우아하게 문제를 해결합니다"}]'::jsonb,
 '[{"name":"배달의민족"},{"name":"배민커넥트"},{"name":"배민상회"}]'::jsonb,
 '[{"icon":"schedule","title":"주 32시간제","desc":"월요일 오후 출근"},{"icon":"school","title":"우아한테크코스","desc":"사내외 교육 프로그램"},{"icon":"menu_book","title":"도서 무제한","desc":"도서 구입비 지원"},{"icon":"restaurant","title":"식사 지원","desc":"점심·저녁 식대"}]'::jsonb,
 '["개발 문화가 잘 알려진 조직","우아한테크세미나 등 기술 공유 활발","주 32시간 근무제 운영","MSA 전환 경험 공유가 많음"]'::jsonb),

('daangn', '당근', 'platform', 'midsize',
 '{frontend,backend,android,ios,devops,data_ai}', '서울',
 '당신 근처의 지역 생활 커뮤니티',
 '지역 기반 중고거래에서 출발해 동네 생활 전반을 다루는 서비스로 확장하고 있습니다. 조직 규모 대비 서비스 사용자 수가 매우 큽니다.',
 '{커뮤니티,중고거래,로컬}', 'https://about.daangn.com', 500, '6,000만원',
 4.5, '{"salary":4.4,"wlb":4.6,"culture":4.7,"growth":4.4}'::jsonb,
 '{"overall":6000,"entry":4500,"top25":8000}'::jsonb, '상시 채용',
 '[{"icon":"handshake","title":"신뢰","desc":"이웃 간 신뢰를 만듭니다"},{"icon":"psychology","title":"자율","desc":"스스로 정하고 책임집니다"},{"icon":"insights","title":"임팩트","desc":"영향이 큰 일을 합니다"},{"icon":"eco","title":"지속가능","desc":"자원 순환에 기여합니다"}]'::jsonb,
 '[{"name":"당근마켓"},{"name":"당근알바"},{"name":"당근비즈니스"}]'::jsonb,
 '[{"icon":"schedule","title":"자율 출퇴근","desc":"코어타임 없는 유연근무"},{"icon":"laptop_mac","title":"장비 자율 선택","desc":"원하는 장비 지원"},{"icon":"school","title":"교육비","desc":"컨퍼런스·강의 지원"},{"icon":"restaurant","title":"식사 지원","desc":"점심 식대"}]'::jsonb,
 '["소규모 조직에서 큰 임팩트","자율성이 높은 문화","로컬 서비스 도메인","기술 블로그·밋업 활발"]'::jsonb),

('toss', '토스', 'fintech', 'large',
 '{frontend,backend,android,ios,devops,data_ai,security,designer}', '서울',
 '금융을 쉽고 간편하게',
 '송금에서 시작해 은행·증권·결제까지 확장한 핀테크 기업입니다. 사일로 조직 구조와 강한 자율·책임 문화로 알려져 있습니다.',
 '{핀테크,금융,결제}', 'https://toss.im', 1800, '7,000만원',
 4.2, '{"salary":4.8,"wlb":3.6,"culture":4.2,"growth":4.6}'::jsonb,
 '{"overall":7000,"entry":5000,"top25":10000}'::jsonb, '상시 채용',
 '[{"icon":"speed","title":"빠른 실행","desc":"빠르게 만들고 검증합니다"},{"icon":"psychology","title":"자율과 책임","desc":"스스로 결정합니다"},{"icon":"forum","title":"투명성","desc":"모든 정보를 공유합니다"},{"icon":"person","title":"고객 중심","desc":"고객 문제에서 출발합니다"}]'::jsonb,
 '[{"name":"토스"},{"name":"토스뱅크"},{"name":"토스증권"},{"name":"토스페이먼츠"}]'::jsonb,
 '[{"icon":"payments","title":"높은 보상","desc":"업계 최상위 연봉·스톡옵션"},{"icon":"restaurant","title":"식사 지원","desc":"삼시세끼 지원"},{"icon":"local_taxi","title":"교통비","desc":"야근 택시비 지원"},{"icon":"schedule","title":"자율 휴가","desc":"무제한 휴가 제도"}]'::jsonb,
 '["사일로 단위의 자율 조직","보상 수준이 업계 최상위권","금융 도메인 경험","성장 속도가 매우 빠름"]'::jsonb),

('samsung-electronics', '삼성전자', 'it_software', 'large',
 '{backend,embedded,devops,data_ai,security,qa}', '경기 수원',
 '글로벌 종합 전자·반도체 기업',
 '반도체, 모바일, 가전을 아우르는 글로벌 제조 기업입니다. 소프트웨어 직군은 임베디드·플랫폼·AI 영역의 비중이 높습니다.',
 '{반도체,모바일,임베디드}', 'https://www.samsung.com/sec', 120000, '9,000만원',
 4.0, '{"salary":4.6,"wlb":3.5,"culture":3.7,"growth":4.0}'::jsonb,
 '{"overall":9000,"entry":5500,"top25":13000}'::jsonb, '공채 중심',
 '[{"icon":"precision_manufacturing","title":"기술 제일","desc":"기술로 승부합니다"},{"icon":"public","title":"글로벌","desc":"세계 시장을 무대로"},{"icon":"groups","title":"인재 제일","desc":"사람이 자산입니다"},{"icon":"verified","title":"품질","desc":"최고 품질을 추구합니다"}]'::jsonb,
 '[{"name":"갤럭시"},{"name":"SmartThings"},{"name":"빅스비"}]'::jsonb,
 '[{"icon":"apartment","title":"기숙사","desc":"사업장 인근 기숙사"},{"icon":"medical_services","title":"의료 지원","desc":"사내 병원 및 건강검진"},{"icon":"school","title":"학자금","desc":"본인·자녀 학자금"},{"icon":"payments","title":"성과급","desc":"OPI·TAI 성과급"}]'::jsonb,
 '["국내 최대 규모의 제조 기업","임베디드·반도체 SW 직군 다수","공채 중심 채용","해외 근무 기회"]'::jsonb),

('sk-hynix', 'SK하이닉스', 'it_software', 'large',
 '{backend,embedded,data_ai,devops,qa}', '경기 이천',
 '메모리 반도체 글로벌 리더',
 'DRAM과 낸드플래시를 중심으로 한 메모리 반도체 기업입니다. 소프트웨어 직군은 공정 데이터 분석과 자동화 영역이 중심입니다.',
 '{반도체,메모리,데이터}', 'https://www.skhynix.com', 30000, '8,500만원',
 4.1, '{"salary":4.7,"wlb":3.8,"culture":3.9,"growth":3.9}'::jsonb,
 '{"overall":8500,"entry":5300,"top25":12000}'::jsonb, '공채 중심',
 '[{"icon":"memory","title":"기술 리더십","desc":"메모리 기술을 선도합니다"},{"icon":"handshake","title":"행복 경영","desc":"구성원 행복을 추구합니다"},{"icon":"eco","title":"지속가능","desc":"친환경 생산을 지향합니다"},{"icon":"groups","title":"협업","desc":"함께 성과를 만듭니다"}]'::jsonb,
 '[{"name":"DRAM"},{"name":"NAND Flash"},{"name":"HBM"}]'::jsonb,
 '[{"icon":"apartment","title":"기숙사","desc":"이천·청주 기숙사"},{"icon":"directions_bus","title":"통근버스","desc":"수도권 통근버스"},{"icon":"school","title":"학자금","desc":"자녀 학자금 지원"},{"icon":"payments","title":"성과급","desc":"PS·PI 성과급"}]'::jsonb,
 '["메모리 반도체 글로벌 2위권","데이터 분석·자동화 직군 확대","공채 중심 채용","이천·청주 사업장 중심"]'::jsonb),

('lg-electronics', 'LG전자', 'it_software', 'large',
 '{backend,embedded,frontend,data_ai,qa}', '서울',
 '고객의 삶을 더 좋게',
 '가전과 전장 사업을 중심으로 한 종합 전자 기업입니다. webOS 등 자체 플랫폼 소프트웨어 조직을 운영합니다.',
 '{가전,전장,임베디드}', 'https://www.lge.co.kr', 35000, '8,000만원',
 4.0, '{"salary":4.3,"wlb":4.0,"culture":3.9,"growth":3.8}'::jsonb,
 '{"overall":8000,"entry":5000,"top25":11000}'::jsonb, '공채 중심',
 '[{"icon":"person","title":"고객 가치","desc":"고객 관점에서 생각합니다"},{"icon":"lightbulb","title":"혁신","desc":"끊임없이 혁신합니다"},{"icon":"handshake","title":"정도경영","desc":"원칙을 지킵니다"},{"icon":"groups","title":"인재","desc":"사람을 키웁니다"}]'::jsonb,
 '[{"name":"LG ThinQ"},{"name":"webOS"}]'::jsonb,
 '[{"icon":"medical_services","title":"건강검진","desc":"본인·배우자 검진"},{"icon":"school","title":"학자금","desc":"자녀 학자금 지원"},{"icon":"beach_access","title":"휴양시설","desc":"콘도·리조트 지원"},{"icon":"schedule","title":"유연근무","desc":"선택적 근로시간제"}]'::jsonb,
 '["가전·전장 소프트웨어 직군","webOS 자체 플랫폼 보유","공채 중심 채용","워라밸 만족도가 상대적으로 높음"]'::jsonb),

('ncsoft', '엔씨소프트', 'game', 'large',
 '{backend,frontend,game,devops,data_ai,qa}', '경기 성남',
 'MMORPG 명가',
 '리니지 시리즈를 비롯한 대규모 온라인 게임을 개발·서비스합니다. 서버 엔지니어링과 대규모 동시접속 처리 경험을 쌓을 수 있습니다.',
 '{게임,MMORPG,서버}', 'https://kr.ncsoft.com', 4000, '7,000만원',
 3.8, '{"salary":4.4,"wlb":3.5,"culture":3.5,"growth":3.7}'::jsonb,
 '{"overall":7000,"entry":4800,"top25":9800}'::jsonb, '상시 채용',
 '[{"icon":"sports_esports","title":"재미","desc":"재미를 만듭니다"},{"icon":"engineering","title":"기술","desc":"대규모 트래픽을 다룹니다"},{"icon":"palette","title":"창작","desc":"세계관을 만듭니다"},{"icon":"groups","title":"협업","desc":"직군을 넘어 협업합니다"}]'::jsonb,
 '[{"name":"리니지"},{"name":"블레이드 & 소울"},{"name":"아이온"}]'::jsonb,
 '[{"icon":"fitness_center","title":"사내 시설","desc":"헬스장·병원·카페"},{"icon":"restaurant","title":"식사 지원","desc":"사내 식당 운영"},{"icon":"medical_services","title":"건강검진","desc":"종합 건강검진"},{"icon":"child_care","title":"어린이집","desc":"사내 어린이집"}]'::jsonb,
 '["국내 대표 MMORPG 개발사","대규모 동시접속 서버 경험","판교 사옥 복지 시설","게임 서버·클라이언트 직군 다수"]'::jsonb),

('nexon', '넥슨코리아', 'game', 'large',
 '{backend,frontend,game,devops,data_ai,qa}', '경기 성남',
 '게임으로 연결되는 즐거움',
 '메이플스토리, 던전앤파이터 등 장수 게임을 운영하는 게임 기업입니다. 라이브 서비스 운영 경험을 쌓기 좋은 환경입니다.',
 '{게임,라이브서비스,데이터}', 'https://www.nexon.com', 3500, '6,800만원',
 4.0, '{"salary":4.3,"wlb":3.9,"culture":3.9,"growth":3.8}'::jsonb,
 '{"overall":6800,"entry":4700,"top25":9200}'::jsonb, '상시 채용',
 '[{"icon":"sports_esports","title":"플레이","desc":"즐거움을 만듭니다"},{"icon":"insights","title":"데이터","desc":"데이터로 판단합니다"},{"icon":"autorenew","title":"라이브","desc":"끊임없이 개선합니다"},{"icon":"groups","title":"동료","desc":"좋은 동료가 됩니다"}]'::jsonb,
 '[{"name":"메이플스토리"},{"name":"던전앤파이터"},{"name":"FC 온라인"}]'::jsonb,
 '[{"icon":"restaurant","title":"식사 지원","desc":"삼시세끼 무료"},{"icon":"child_care","title":"어린이집","desc":"사내 어린이집 운영"},{"icon":"medical_services","title":"의료 지원","desc":"사내 의원 운영"},{"icon":"schedule","title":"유연근무","desc":"선택적 근로시간제"}]'::jsonb,
 '["장수 라이브 게임 다수 운영","데이터 분석 직군 활발","판교 사옥 복지 우수","게임 데이터 플랫폼 경험"]'::jsonb),

('krafton', '크래프톤', 'game', 'large',
 '{backend,game,devops,data_ai,security}', '서울',
 '게임을 통해 세상과 소통',
 '배틀그라운드를 개발한 게임 기업입니다. 글로벌 이용자를 대상으로 서비스하며 해외 협업 비중이 높습니다.',
 '{게임,글로벌,배틀로얄}', 'https://www.krafton.com', 1800, '7,500만원',
 4.1, '{"salary":4.6,"wlb":3.9,"culture":4.0,"growth":4.1}'::jsonb,
 '{"overall":7500,"entry":5200,"top25":10500}'::jsonb, '상시 채용',
 '[{"icon":"public","title":"글로벌","desc":"세계를 대상으로 만듭니다"},{"icon":"emoji_objects","title":"창의","desc":"새로운 재미를 찾습니다"},{"icon":"engineering","title":"기술","desc":"기술로 한계를 넘습니다"},{"icon":"psychology","title":"자율","desc":"스튜디오 단위 자율"}]'::jsonb,
 '[{"name":"PUBG: 배틀그라운드"},{"name":"배틀그라운드 모바일"}]'::jsonb,
 '[{"icon":"payments","title":"높은 보상","desc":"게임업계 상위 연봉"},{"icon":"restaurant","title":"식사 지원","desc":"식대 지원"},{"icon":"flight","title":"해외 협업","desc":"글로벌 스튜디오 교류"},{"icon":"schedule","title":"유연근무","desc":"자율 출퇴근"}]'::jsonb,
 '["글로벌 흥행 IP 보유","해외 이용자 대상 서비스","스튜디오 독립 운영 구조","보상 수준이 게임업계 상위권"]'::jsonb),

('smilegate', '스마일게이트', 'game', 'large',
 '{backend,frontend,game,devops,qa}', '경기 성남',
 '글로벌 게임 퍼블리셔',
 '크로스파이어와 로스트아크를 서비스하는 게임 기업입니다. 개발·퍼블리싱·투자 부문이 그룹 형태로 구성되어 있습니다.',
 '{게임,퍼블리싱,글로벌}', 'https://www.smilegate.com', 2500, '6,500만원',
 4.0, '{"salary":4.2,"wlb":4.0,"culture":4.0,"growth":3.9}'::jsonb,
 '{"overall":6500,"entry":4600,"top25":8800}'::jsonb, '상시 채용',
 '[{"icon":"sports_esports","title":"재미","desc":"즐거움을 전합니다"},{"icon":"public","title":"글로벌","desc":"해외 시장을 개척합니다"},{"icon":"volunteer_activism","title":"나눔","desc":"사회 공헌을 실천합니다"},{"icon":"groups","title":"동료","desc":"함께 만듭니다"}]'::jsonb,
 '[{"name":"크로스파이어"},{"name":"로스트아크"},{"name":"에픽세븐"}]'::jsonb,
 '[{"icon":"restaurant","title":"식사 지원","desc":"사내 식당 운영"},{"icon":"fitness_center","title":"사내 시설","desc":"헬스장·카페"},{"icon":"school","title":"교육 지원","desc":"직무 교육비"},{"icon":"medical_services","title":"건강검진","desc":"종합 건강검진"}]'::jsonb,
 '["해외 매출 비중이 높은 게임사","로스트아크 라이브 서비스","판교 사옥 근무","퍼블리싱 직군도 다수"]'::jsonb),

('estsoft', '이스트소프트', 'it_software', 'midsize',
 '{frontend,backend,data_ai,security,qa}', '서울',
 'AI 중심의 소프트웨어 기업',
 'AI와 소프트웨어 기술을 기반으로 보안, 유틸리티, 포털, AI 휴먼 서비스를 제공합니다. 30년 이상 축적된 소프트웨어 기술력을 보유하고 있습니다.',
 '{AI,보안,유틸리티}', 'https://estsoft.ai', 550, '5,000만원',
 4.0, '{"salary":3.9,"wlb":4.2,"culture":4.1,"growth":4.0}'::jsonb,
 '{"overall":5000,"entry":3800,"top25":6800}'::jsonb, '상시 채용',
 '[{"icon":"psychology","title":"기술 혁신","desc":"끊임없이 연구합니다"},{"icon":"school","title":"성장","desc":"개인의 성장을 지원합니다"},{"icon":"groups","title":"협업","desc":"함께 문제를 풉니다"},{"icon":"verified","title":"신뢰","desc":"안전한 소프트웨어를 만듭니다"}]'::jsonb,
 '[{"name":"알약"},{"name":"알집"},{"name":"줌(ZUM)"},{"name":"AI 스튜디오"}]'::jsonb,
 '[{"icon":"restaurant","title":"식대 지원","desc":"중식 및 석식 지원"},{"icon":"medical_services","title":"건강검진","desc":"건강검진·의료비 지원"},{"icon":"school","title":"교육비 지원","desc":"직무 교육 및 도서"},{"icon":"child_care","title":"육아 지원","desc":"육아휴직·출산 경조사"}]'::jsonb,
 '["AI 중심의 소프트웨어 기업","AI·보안·유틸리티 서비스 제공","다양한 IT 직군 채용","30년 이상의 IT 기술력"]'::jsonb),

('ahnlab', '안랩', 'security', 'midsize',
 '{backend,security,devops,qa,embedded}', '경기 성남',
 '국내 대표 정보보안 기업',
 '백신 V3를 비롯한 정보보안 솔루션과 관제 서비스를 제공합니다. 보안 분야로 커리어를 시작하기 좋은 환경입니다.',
 '{보안,관제,백신}', 'https://www.ahnlab.com', 1200, '5,500만원',
 3.9, '{"salary":3.8,"wlb":4.1,"culture":4.0,"growth":3.8}'::jsonb,
 '{"overall":5500,"entry":4000,"top25":7200}'::jsonb, '상시 채용',
 '[{"icon":"shield","title":"보안","desc":"안전한 세상을 만듭니다"},{"icon":"psychology","title":"전문성","desc":"깊이 있는 기술을 추구합니다"},{"icon":"handshake","title":"신뢰","desc":"고객의 신뢰를 지킵니다"},{"icon":"school","title":"성장","desc":"보안 전문가를 양성합니다"}]'::jsonb,
 '[{"name":"V3"},{"name":"AhnLab EDR"},{"name":"AhnLab MDS"}]'::jsonb,
 '[{"icon":"school","title":"자격증 지원","desc":"보안 자격증 취득 지원"},{"icon":"restaurant","title":"식사 지원","desc":"식대 지원"},{"icon":"medical_services","title":"건강검진","desc":"종합 건강검진"},{"icon":"schedule","title":"유연근무","desc":"시차 출퇴근제"}]'::jsonb,
 '["국내 정보보안 대표 기업","보안 관제·분석 직군 다수","자격증 취득 지원 제도","판교 사옥 근무"]'::jsonb),

('yanolja', '야놀자', 'platform', 'large',
 '{frontend,backend,android,ios,devops,data_ai}', '서울',
 '여가와 여행을 더 쉽게',
 '숙박·레저 예약 플랫폼에서 출발해 글로벌 호스피탈리티 솔루션으로 확장하고 있습니다. B2C와 B2B SaaS를 함께 다룹니다.',
 '{여행,플랫폼,SaaS}', 'https://www.yanolja.com', 1500, '6,000만원',
 3.9, '{"salary":4.2,"wlb":3.8,"culture":3.8,"growth":4.0}'::jsonb,
 '{"overall":6000,"entry":4400,"top25":8300}'::jsonb, '상시 채용',
 '[{"icon":"flight_takeoff","title":"여가","desc":"쉼을 더 쉽게 만듭니다"},{"icon":"public","title":"글로벌","desc":"세계 시장으로 확장합니다"},{"icon":"insights","title":"데이터","desc":"데이터로 개선합니다"},{"icon":"speed","title":"실행","desc":"빠르게 시도합니다"}]'::jsonb,
 '[{"name":"야놀자"},{"name":"야놀자 클라우드"},{"name":"인터파크 트리플"}]'::jsonb,
 '[{"icon":"hotel","title":"숙박 지원","desc":"제휴 숙소 할인"},{"icon":"restaurant","title":"식사 지원","desc":"식대 지원"},{"icon":"schedule","title":"유연근무","desc":"자율 출퇴근"},{"icon":"school","title":"교육 지원","desc":"직무 교육비"}]'::jsonb,
 '["B2C 플랫폼과 B2B SaaS 병행","글로벌 확장 진행 중","여행·여가 도메인","데이터 직군 채용 활발"]'::jsonb),

('musinsa', '무신사', 'ecommerce', 'large',
 '{frontend,backend,android,ios,devops,data_ai,designer}', '서울',
 '패션에 미치다',
 '패션 전문 이커머스 플랫폼입니다. 커머스 트래픽과 물류, 추천 시스템을 함께 다룰 수 있습니다.',
 '{패션,커머스,추천}', 'https://www.musinsa.com', 1200, '5,800만원',
 4.0, '{"salary":4.1,"wlb":3.9,"culture":4.0,"growth":4.1}'::jsonb,
 '{"overall":5800,"entry":4300,"top25":7800}'::jsonb, '상시 채용',
 '[{"icon":"styler","title":"패션","desc":"스타일을 제안합니다"},{"icon":"insights","title":"데이터","desc":"취향을 데이터로 읽습니다"},{"icon":"speed","title":"속도","desc":"빠르게 실험합니다"},{"icon":"groups","title":"협업","desc":"직군을 넘어 협업합니다"}]'::jsonb,
 '[{"name":"무신사 스토어"},{"name":"29CM"},{"name":"무신사 스탠다드"}]'::jsonb,
 '[{"icon":"local_offer","title":"임직원 할인","desc":"무신사 스토어 할인"},{"icon":"restaurant","title":"식사 지원","desc":"식대 지원"},{"icon":"schedule","title":"유연근무","desc":"자율 출퇴근"},{"icon":"school","title":"교육 지원","desc":"직무 교육비"}]'::jsonb,
 '["국내 최대 패션 커머스","추천·검색 시스템 개발","임직원 할인 혜택","성수 사옥 근무"]'::jsonb),

('kurly', '컬리', 'ecommerce', 'large',
 '{frontend,backend,android,ios,devops,data_ai}', '서울',
 '내일의 장보기, 마켓컬리',
 '신선식품 새벽배송으로 알려진 이커머스 기업입니다. 물류 최적화와 수요 예측 등 데이터 문제를 다룹니다.',
 '{신선식품,물류,데이터}', 'https://www.kurly.com', 1500, '5,600만원',
 3.8, '{"salary":4.0,"wlb":3.7,"culture":3.8,"growth":3.9}'::jsonb,
 '{"overall":5600,"entry":4200,"top25":7500}'::jsonb, '상시 채용',
 '[{"icon":"eco","title":"품질","desc":"좋은 상품만 제안합니다"},{"icon":"insights","title":"데이터","desc":"수요를 예측합니다"},{"icon":"local_shipping","title":"물류","desc":"새벽배송을 최적화합니다"},{"icon":"person","title":"고객","desc":"고객 경험을 우선합니다"}]'::jsonb,
 '[{"name":"마켓컬리"},{"name":"뷰티컬리"}]'::jsonb,
 '[{"icon":"local_offer","title":"임직원 할인","desc":"컬리 구매 할인"},{"icon":"restaurant","title":"식사 지원","desc":"식대 지원"},{"icon":"medical_services","title":"건강검진","desc":"종합 건강검진"},{"icon":"schedule","title":"유연근무","desc":"시차 출퇴근제"}]'::jsonb,
 '["신선식품 새벽배송 선도","수요 예측·물류 최적화 문제","데이터 엔지니어링 직군","임직원 구매 할인"]'::jsonb),

('zigbang', '직방', 'platform', 'midsize',
 '{frontend,backend,android,ios,data_ai}', '서울',
 '집 구하는 사람들의 필수 앱',
 '부동산 정보 플랫폼입니다. 매물 데이터 수집·검증과 지도 기반 서비스 개발 경험을 쌓을 수 있습니다.',
 '{부동산,플랫폼,지도}', 'https://www.zigbang.com', 400, '5,500만원',
 3.9, '{"salary":4.0,"wlb":4.1,"culture":4.0,"growth":3.7}'::jsonb,
 '{"overall":5500,"entry":4100,"top25":7300}'::jsonb, '상시 채용',
 '[{"icon":"home","title":"주거","desc":"더 나은 집을 찾아줍니다"},{"icon":"verified","title":"신뢰","desc":"허위 매물을 걸러냅니다"},{"icon":"map","title":"공간 데이터","desc":"지도 위에서 문제를 풉니다"},{"icon":"psychology","title":"자율","desc":"스스로 판단합니다"}]'::jsonb,
 '[{"name":"직방"},{"name":"호갱노노"},{"name":"온택트파트너스"}]'::jsonb,
 '[{"icon":"laptop_mac","title":"원격근무","desc":"메타버스 기반 원격근무"},{"icon":"restaurant","title":"식사 지원","desc":"식대 지원"},{"icon":"school","title":"교육 지원","desc":"직무 교육비"},{"icon":"schedule","title":"유연근무","desc":"자율 출퇴근"}]'::jsonb,
 '["부동산 데이터 플랫폼","지도·공간 데이터 개발","원격근무 제도 운영","소규모 조직 구조"]'::jsonb)

on conflict (slug) do update set
  name = excluded.name,
  industry_code = excluded.industry_code,
  size_code = excluded.size_code,
  job_role_codes = excluded.job_role_codes,
  location = excluded.location,
  tagline = excluded.tagline,
  description = excluded.description,
  tags = excluded.tags,
  homepage = excluded.homepage,
  employee_count = excluded.employee_count,
  avg_salary_text = excluded.avg_salary_text,
  rating = excluded.rating,
  rating_dimensions = excluded.rating_dimensions,
  salary_detail = excluded.salary_detail,
  hiring_status = excluded.hiring_status,
  core_values = excluded.core_values,
  services = excluded.services,
  benefits = excluded.benefits,
  highlights = excluded.highlights;

update public.companies c
set logo_url = v.logo_url
from (values
  ('naver'), ('kakao'), ('line'), ('coupang'), ('woowahan'), ('daangn'), ('toss'),
  ('samsung-electronics'), ('sk-hynix'), ('lg-electronics'), ('ncsoft'), ('nexon'),
  ('krafton'), ('smilegate'), ('estsoft'), ('ahnlab'), ('yanolja'), ('musinsa'),
  ('kurly'), ('zigbang')
) as s(slug)
cross join lateral (select s.slug, '/images/companies/' || s.slug || '.svg' as logo_url) v
where c.slug = s.slug;

update public.companies c
set ceo = v.ceo, founded_on = v.founded_on, hq_address = v.hq_address
from (values
  ('naver',   '최수연', date '1999-06-02', '경기 성남시 분당구 정자일로 95'),
  ('kakao',   '정신아', null::date,        null),
  ('coupang', '김범석', null::date,        null),
  ('estsoft', '김장중', date '1993-10-02', '서울 서초구 반포대로 3')
) as v(slug, ceo, founded_on, hq_address)
where c.slug = v.slug;

update public.companies c
set news = v.news
from (values
  ('naver', '[{"title":"\"AI 시대에도 블로그 창작자 수익 늘었다\"… 네이버, AI 브리핑 도입 이후 창작자 지원 규모 약 2배 확대","url":"https://www.navercorp.com/media/pressReleasesDetail?seq=10034578","published_on":"2026-08-07"},{"title":"네이버, 2026년 2분기 매출액 3조 3,888억 원, 영업이익 5,203억 원 기록","url":"https://www.navercorp.com/media/pressReleasesDetail?seq=10034577","published_on":"2026-08-07"},{"title":"네이버웹툰 日 라인망가, NTT도코모와 손잡고 애니메이션 구독 서비스 선보인다","url":"https://www.navercorp.com/media/pressReleasesDetail?seq=10034556","published_on":"2026-08-05"}]'::jsonb),
  ('coupang', '[{"title":"\"직원 안전보건 지킴이\" 쿠팡 물류 현장 누비는 ''녹색조끼 간호사'' 이야기","url":"https://news.coupang.com/archives/64644/","published_on":"2026-08-06"},{"title":"''잠시 멈춤, 나의 속도로'' 쿠팡로지스틱스서비스 배송기사들의 휴가 이야기","url":"https://news.coupang.com/archives/65074/","published_on":"2026-08-04"},{"title":"\"건강도 챙기고 기부도 하고\" 2026 쿠팡 글로벌 워킹 챌린지","url":"https://news.coupang.com/archives/64963/","published_on":"2026-07-31"}]'::jsonb),
  ('sk-hynix', '[{"title":"SK하이닉스, 용인 Y2 ∙ 청주 M17에 54조 원 투자… AI 시대 메모리 수요 대응 위한 중장기 생산 기반 확보","url":"https://news.skhynix.co.kr/fab-facility-investment-2026/","published_on":"2026-08-07"},{"title":"AI 시대, 차세대 메모리 아키텍처는?… SK하이닉스, ''FMS 2026''서 방향성 제시","url":"https://news.skhynix.co.kr/fms-2026/","published_on":"2026-08-07"},{"title":"SK하이닉스, 샌디스크와 HBF 첫 표준 규격 공개…''FMS 2026''서 AI 메모리 해법 알린다","url":"https://news.skhynix.co.kr/hbf-at-fms-2026/","published_on":"2026-08-04"}]'::jsonb)
) as v(slug, news)
where c.slug = v.slug;

update public.companies c
set logo_url = 'https://cbidaboiqbkxexxbunsx.supabase.co/storage/v1/object/public/company-logos/'
               || c.slug || '.svg'
where exists (
  select 1 from storage.objects o
  where o.bucket_id = 'company-logos' and o.name = c.slug || '.svg'
);
