insert into public.resume_templates (title, doc_type, category_code, thumbnail_url, content_html, view_count, sort_order) values
  ('기본 이력서', 'resume', 'basic', '/images/templates/resume-basic.svg', '<h1>홍길동</h1><p><em>프론트엔드 개발자</em></p><h2>인적사항</h2><table><tbody><tr><td>이메일</td><td>hong@example.com</td></tr><tr><td>연락처</td><td>010-0000-0000</td></tr><tr><td>깃허브</td><td>github.com/hong</td></tr></tbody></table><h2>학력</h2><table><tbody><tr><td>2020.03 – 2024.02</td><td>○○대학교 소프트웨어학과 (졸업)</td></tr></tbody></table><h2>경력</h2><table><tbody><tr><td>2024.03 – 재직 중</td><td>○○○ / 프론트엔드 개발</td></tr></tbody></table><h2>기술 스택</h2><ul><li>JavaScript, TypeScript</li><li>React, Next.js</li><li>Git, Figma</li></ul><h2>자격 및 어학</h2><table><tbody><tr><td>2024.06</td><td>정보처리기사</td></tr><tr><td>2024.09</td><td>OPIc IH</td></tr></tbody></table>', 3290, 1),
  ('신입 개발자 이력서', 'resume', 'newcomer', '/images/templates/resume-newcomer.svg', '<h1>홍길동</h1><p><em>신입 백엔드 개발자를 지원합니다</em></p><h2>한 줄 소개</h2><p>사용자 문제를 데이터로 정의하고 코드로 푸는 것을 좋아합니다.</p><h2>학력</h2><table><tbody><tr><td>2020.03 – 2026.02</td><td>○○대학교 컴퓨터공학과 (졸업예정)</td></tr></tbody></table><h2>프로젝트</h2><p><strong>프로젝트명</strong> · 2026.01 – 2026.02 · 팀 4명</p><ul><li>맡은 역할과 기술을 한 줄로</li><li>수치로 표현한 성과</li><li>겪은 문제와 해결 방법</li></ul><h2>교육 및 활동</h2><table><tbody><tr><td>2025.06 – 2025.12</td><td>○○ 부트캠프 수료</td></tr></tbody></table><h2>기술 스택</h2><ul><li>Java, Spring Boot</li><li>MySQL, Redis</li><li>Docker, AWS</li></ul>', 2870, 2),
  ('경력 개발자 이력서', 'resume', 'career', '/images/templates/resume-career.svg', '<h1>홍길동</h1><p><em>5년차 백엔드 개발자</em></p><h2>경력 요약</h2><ul><li>대용량 트래픽 서비스 설계 및 운영 3년</li><li>팀 리딩 및 코드 리뷰 문화 정착</li><li>MSA 전환 프로젝트 리드</li></ul><h2>경력</h2><p><strong>○○○</strong> · 백엔드 개발 · 2022.01 – 재직 중</p><ul><li>담당 서비스와 규모</li><li>개선 지표 (응답속도 40% 단축 등)</li><li>사용 기술</li></ul><p><strong>△△△</strong> · 백엔드 개발 · 2020.03 – 2021.12</p><ul><li>담당 업무</li><li>성과</li></ul><h2>기술 스택</h2><ul><li>Java, Kotlin, Spring</li><li>PostgreSQL, Kafka</li><li>Kubernetes, AWS</li></ul><h2>학력</h2><table><tbody><tr><td>2016.03 – 2020.02</td><td>○○대학교 컴퓨터공학과 (졸업)</td></tr></tbody></table>', 2410, 3),
  ('프로젝트 중심 이력서', 'resume', 'project', '/images/templates/resume-project.svg', '<h1>홍길동</h1><p><em>만든 것으로 말합니다</em></p><h2>대표 프로젝트</h2><p><strong>프로젝트 A</strong> · 2026.01 – 2026.03</p><ul><li>문제: 무엇이 불편했는가</li><li>해결: 어떻게 접근했는가</li><li>결과: 어떤 수치가 바뀌었는가</li><li>기술: React, Next.js, Supabase</li></ul><h2>그 외 프로젝트</h2><table><tbody><tr><td>프로젝트 B</td><td>한 줄 설명 · 기술 스택</td></tr><tr><td>프로젝트 C</td><td>한 줄 설명 · 기술 스택</td></tr></tbody></table><h2>경력 · 학력</h2><table><tbody><tr><td>2024.03 – 재직 중</td><td>○○○ / 프론트엔드</td></tr><tr><td>2020.03 – 2024.02</td><td>○○대학교 소프트웨어학과</td></tr></tbody></table>', 1980, 4),
  ('포트폴리오형 이력서', 'resume', 'portfolio', '/images/templates/resume-portfolio.svg', '<h1>홍길동</h1><p><em>프론트엔드 · UI 엔지니어</em></p><h2>링크</h2><ul><li>포트폴리오: portfolio.example.com</li><li>GitHub: github.com/hong</li><li>블로그: blog.example.com</li></ul><h2>주요 작업물</h2><p><strong>작업물 1</strong></p><ul><li>역할과 사용 기술</li><li>화면 또는 데모 링크</li></ul><h2>경력</h2><table><tbody><tr><td>2023.06 – 재직 중</td><td>○○○ / 프론트엔드 개발</td></tr></tbody></table><h2>기술 스택</h2><ul><li>React, Next.js, TypeScript</li><li>Sass, Tailwind</li><li>Figma</li></ul>', 1640, 5),
  ('국문 표준 이력서', 'resume', 'standard', '/images/templates/resume-standard.svg', '<h1>이 력 서</h1><p><em></em></p><h2>인적사항</h2><table><tbody><tr><td>성명</td><td>홍길동</td></tr><tr><td>생년월일</td><td>2000.01.01</td></tr><tr><td>주소</td><td>서울특별시 ○○구</td></tr><tr><td>연락처</td><td>010-0000-0000</td></tr><tr><td>이메일</td><td>hong@example.com</td></tr></tbody></table><h2>학력사항</h2><table><tbody><tr><td>기간</td><td>학교명</td><td>전공</td><td>비고</td></tr><tr><td>2020.03 – 2024.02</td><td>○○대학교</td><td>컴퓨터공학과</td><td>졸업</td></tr></tbody></table><h2>경력사항</h2><table><tbody><tr><td>기간</td><td>회사명</td><td>담당업무</td><td>비고</td></tr><tr><td>2024.03 – 현재</td><td>○○○</td><td>백엔드 개발</td><td>재직</td></tr></tbody></table><h2>자격사항</h2><table><tbody><tr><td>취득일</td><td>자격명</td><td>발급기관</td></tr><tr><td>2024.06</td><td>정보처리기사</td><td>한국산업인력공단</td></tr></tbody></table>', 1320, 6),
  ('영문 이력서 (English Resume)', 'resume', 'english', '/images/templates/resume-english.svg', '<h1>Gildong Hong</h1><p><em>Frontend Engineer</em></p><h2>Contact</h2><ul><li>hong@example.com</li><li>github.com/hong</li><li>Seoul, Korea</li></ul><h2>Summary</h2><p>Frontend engineer with 3 years of experience building web products with React and TypeScript.</p><h2>Experience</h2><p><strong>Company</strong> · Frontend Engineer · Mar 2024 – Present</p><ul><li>What you owned</li><li>Impact with numbers</li><li>Tech used</li></ul><h2>Skills</h2><ul><li>JavaScript, TypeScript</li><li>React, Next.js</li><li>Testing, CI/CD</li></ul><h2>Education</h2><table><tbody><tr><td>Mar 2020 – Feb 2024</td><td>B.S. in Computer Science, ○○ University</td></tr></tbody></table>', 980, 7),
  ('기본 자기소개서', 'cover_letter', 'basic', '/images/templates/cover-basic.svg', '<h1>자기소개서</h1><p><em>지원 직무: 프론트엔드 개발</em></p><h2>지원 동기</h2><p>회사의 어떤 점에 끌렸는지, 내 경험과 어떻게 연결되는지 3~4문장으로 씁니다.</p><h2>성장 과정</h2><p>직무와 연결되는 경험 한 가지를 골라 구체적으로 씁니다.</p><h2>직무 역량</h2><p>맡았던 일 → 문제 → 행동 → 결과 순서로 씁니다. 수치가 있으면 반드시 넣습니다.</p><h2>입사 후 포부</h2><p>1년 안에 하고 싶은 일과 3년 뒤의 목표를 씁니다.</p>', 3120, 1),
  ('신입 자기소개서', 'cover_letter', 'newcomer', '/images/templates/cover-newcomer.svg', '<h1>자기소개서</h1><p><em>신입 지원</em></p><h2>나를 한 문장으로</h2><p>"○○한 개발자"라고 정의하고, 그 근거를 아래에서 증명합니다.</p><h2>가장 몰입했던 경험</h2><p>언제, 무엇을, 왜 했는지. 어려웠던 점과 해결 과정을 씁니다.</p><h2>협업 경험</h2><p>팀에서 맡은 역할과 갈등을 조율한 방법을 씁니다.</p><h2>지원 동기와 포부</h2><p>왜 이 회사, 왜 이 직무인지 연결해서 씁니다.</p>', 2760, 2),
  ('경력 자기소개서', 'cover_letter', 'career', '/images/templates/cover-career.svg', '<h1>자기소개서</h1><p><em>경력 지원</em></p><h2>경력 요약</h2><p>몇 년간 어떤 도메인에서 무엇을 했는지 3문장으로 압축합니다.</p><h2>대표 성과</h2><p>가장 큰 임팩트를 낸 일 하나를 골라 문제·행동·결과로 씁니다.</p><h2>이직 사유</h2><p>부정적 표현 없이, 앞으로 하고 싶은 일 중심으로 씁니다.</p><h2>기여 계획</h2><p>입사 후 첫 3개월 / 1년에 무엇을 할지 씁니다.</p>', 2050, 3),
  ('직무 역량 중심 자기소개서', 'cover_letter', 'competency', '/images/templates/cover-competency.svg', '<h1>자기소개서</h1><p><em>직무 역량 중심</em></p><h2>핵심 역량 1</h2><p>역량명을 소제목처럼 쓰고, 근거가 되는 경험을 붙입니다.</p><h2>핵심 역량 2</h2><p>가능하면 서로 다른 종류의 역량을 고릅니다. (기술 / 협업 / 문제해결)</p><h2>핵심 역량 3</h2><p>직무 공고의 자격 요건에서 키워드를 가져와 맞춥니다.</p><h2>마무리</h2><p>세 역량이 이 직무에서 어떻게 쓰일지 연결합니다.</p>', 1710, 4),
  ('프로젝트 경험 중심 자기소개서', 'cover_letter', 'project', '/images/templates/cover-project.svg', '<h1>자기소개서</h1><p><em>프로젝트 경험 중심</em></p><h2>프로젝트 개요</h2><p>무엇을 만들었고, 팀 규모와 기간은 어땠는지 씁니다.</p><h2>내가 맡은 부분</h2><p>"우리"가 아니라 "내가" 무엇을 했는지 명확히 씁니다.</p><h2>가장 어려웠던 문제</h2><p>문제 상황 → 시도한 방법 → 최종 해결 → 배운 점 순서로 씁니다.</p><h2>이 경험을 어떻게 쓸 것인가</h2><p>지원 직무와 연결합니다.</p>', 1450, 5)
on conflict (doc_type, title) do update set
  category_code = excluded.category_code,
  thumbnail_url = excluded.thumbnail_url,
  content_html = excluded.content_html,
  view_count = excluded.view_count,
  sort_order = excluded.sort_order,
  is_active = true;
